# docs/swagger.yml

openapi: 3.0.0
info:
  title: Login API
  version: 1.0.0
paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "João Silva"
                email:
                  type: string
                  example: "joao.silva@example.com"
                password:
                  type: string
                  example: "securePassword123"
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
        '400':
          description: Invalid input data (e.g., missing fields, invalid email)
        '409':
          description: User with this email already exists
  /auth/login:
    post:
      summary: Log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "joao.silva@example.com"
                password:
                  type: string
                  example: "securePassword123"

      responses:
        '200':
          description: User logged in successfully